// Interface strings. Prose lives in content/; this file is chrome only:
// menu labels, table headers, captions and the fixed notes that sit under
// generated tables. English is the source; a missing Ukrainian key falls back
// to English rather than failing the build (CLAUDE.md 2).
const en = {
  "skip": "Skip to content",
  "menu": "Menu",
  "nav.main": "Main",
  "nav.footer": "Footer",
  "nav.breadcrumb": "Breadcrumb",
  "nav.pageData": "This page as data",
  "nav.contents": "Contents",

  "crumb.home": "Home",
  "crumb.registry": "Registry",
  "crumb.sources": "Sources",
  "crumb.escalations": "Escalations",
  "crumb.methodology": "Methodology",
  "crumb.data": "Data",
  "crumb.about": "About",
  "crumb.reports": "Reports",
  "crumb.chatbots": "Chatbots",

  "updated.prefix": "Updated",
  "updated.licence": "Data:",
  "updated.how": "How we measure",
  "footer.pageData": "This page as data:",
  "footer.licence": "Data under",

  "translation.missing": "This page has not been translated into Ukrainian yet. The text below is the English original; the figures and dates are the same in both languages.",

  "action.browseRegistry": "Browse the registry",
  "action.readReport": "Read the latest report",
  "action.escalationLog": "See the escalation log",
  "action.whoWeAre": "Who we are",
  "action.allClaims": "All claims",
  "action.allInRegistry": "All %s claims in the registry",
  "action.allDomains": "All %s domains on the watchlist",
  "action.whatThisDomainIs": "what this domain is",

  "counter.claims": "false claims documented",
  "counter.claimsFew": "false claims documented",
  "counter.claim": "false claim documented",
  "counter.answers": "chatbot answers analysed",
  "counter.answersFew": "chatbot answers analysed",
  "counter.answer": "chatbot answer analysed",
  "counter.reports": "reports sent to platforms",
  "counter.reportsFew": "reports sent to platforms",
  "counter.report": "report sent to platforms",
  "counter.actionsLogged": "actions logged",
  "counter.reportsSent": "reports sent",
  "counter.answered": "answered",
  "counter.confirmedChanges": "confirmed changes",

  "col.claim": "Claim",
  "col.cluster": "Cluster",
  "col.verdict": "Verdict",
  "col.repeatedBy": "Repeated by",
  "col.countries": "Countries",
  "col.country": "Country",
  "col.escalation": "Escalation",
  "col.updated": "Updated",
  "col.chatbot": "Chatbot",
  "col.company": "Company",
  "col.language": "Language",
  "col.persona": "Persona",
  "col.date": "Date",
  "col.modelVersion": "Model version",
  "col.behaviour": "Behaviour",
  "col.citedDomains": "Kremlin-linked domains cited",
  "col.organisation": "Organisation",
  "col.finding": "Finding",
  "col.action": "Action",
  "col.to": "To",
  "col.status": "Status",
  "col.response": "Response",
  "col.answers": "Answers",
  "col.repeated": "Repeated",
  "col.contextualised": "Contextualised",
  "col.refuted": "Refuted",
  "col.dodged": "Dodged",
  "col.repeatRate": "Repeat-rate",
  "col.before": "Before",
  "col.after": "After",
  "col.change": "Change",
  "col.measured": "Measured",
  "col.remeasured": "Re-measured",
  "col.month": "Month",
  "col.domain": "Domain",
  "col.firstSeen": "First seen cited",
  "col.claims": "Claims",
  "col.citedBy": "Cited by",
  "col.complaint": "Complaint",
  "col.dataset": "Dataset",
  "col.format": "Format",
  "col.contains": "What it contains",
  "col.report": "Report",
  "col.publishedOn": "Published",
  "col.chatbots": "Chatbots",
  "col.count": "Count",
  "col.citedWatchlisted": "Cited a watchlisted domain",

  "value.none": "none",
  "value.notReported": "not reported",
  "value.notRecorded": "not recorded",
  "value.noneFiled": "none filed",
  "value.na": "n/a",
  "value.dash": "—",

  "claim.verdict": "The verdict",
  "claim.whatIsTrue": "What is true",
  "claim.origin": "Where the claim comes from",
  "claim.whoElse": "Who else has checked this",
  "claim.whichChatbots": "Which chatbots repeated it",
  "claim.sourcesCited": "Sources the chatbots cited",
  "claim.whatWeDid": "What we did",
  "claim.whatChanged": "What changed",
  "claim.changelog": "Changelog",
  "claim.cite": "Cite this page",
  "claim.related": "Related claims",
  "claim.official": "official",
  "claim.cluster": "Cluster",
  "claim.verdictIssued": "Verdict",
  "claim.id": "ID",

  "caption.observations": "Every answer we recorded for this claim. One row per answer; personas are never averaged.",
  "caption.confirmations": "Independent organisations that reached the same conclusion.",
  "caption.actions": "Everything we did about this claim, with dates.",
  "caption.beforeAfter": "Repeat-rate before and after we reported this claim, per chatbot and per persona.",
  "caption.claims": "Every documented claim, most recently updated first.",
  "caption.facetClaims": "Claims in this view, most recently updated first.",
  "caption.registration": "Registration and status.",
  "caption.contact": "Where to write.",
  "caption.datasets": "Every dataset published from this site. All under CC BY 4.0.",
  "caption.escalationLog": "Every action, newest first. Status wording is fixed; nothing is logged as in progress without a date.",
  "caption.actionsByType": "What kind of action we took, and how often.",
  "caption.reports": "Every report in the series, newest first.",
  "caption.scope": "What this run covered.",
  "caption.byChatbotPersona": "One row per chatbot and persona. Repeat-rate is repeated over non-evasive answers; dodged answers are excluded from that denominator and shown separately.",
  "caption.byCountryPersona": "The same answers grouped by the country the session was run from.",
  "caption.layerB": "Answers citing a watchlisted domain, per chatbot and persona.",
  "caption.byMonth": "Behaviour per month and persona. Repeat-rate is repeated over non-evasive answers.",
  "caption.platformClaims": "Documented claims this chatbot stated as fact in at least one recorded answer.",
  "caption.platformEscalations": "Reports sent about findings on this product, with the response status.",
  "caption.platformBeforeAfter": "Repeat-rate before and after each report, with the model version at both measurements.",
  "caption.countryClaims": "Documented claims we recorded in answers served to this country.",
  "caption.platformIndex": "Every chatbot with recorded answers. Counts, not averaged rates: per-persona rates are on each profile.",
  "caption.attribution": "Who attributed this domain to a network, and when.",
  "caption.sourceClaims": "Claims whose recorded answers cited this domain.",
  "caption.complaints": "Abuse complaints we filed about this domain.",
  "caption.watchlist": "Domains attributed to the %s network, most cited first.",

  "note.persona": "Personas are four ways of asking the same question, from a neutral check to a request to write the narrative. Each row is one answer under one persona; we do not average across them, because a model can hold under a neutral question and give way under a leading one.",
  "note.disclosure": "We publish what we did, to whom, and when. We do not publish correspondence or the names of individuals at platforms.",
  "note.causation": "Models are updated continuously and independently of our reports. We record the version at both measurements and publish the change without claiming causation we cannot demonstrate.",
  "note.defang": "Domains are printed defanged and never linked, so this page passes them no authority.",
  "note.publicInterface": "We test the public consumer interface, not the API. Versions are recorded as the product reported them, and results can change when the product is updated.",
  "note.metric": "We report the change in repeat-rate before and after, per chatbot, and per persona.",

  "section.filter": "Filter",
  "section.howToRead": "How to read this registry",
  "section.allClaims": "All claims",
  "section.findings": "What we have found so far",
  "section.usedBy": "Where our data is used",
  "section.whyTrust": "Why trust this",
  "section.theProblem": "The audience is the model",
  "section.whatWeDo": "What we do",
  "section.downloads": "Downloads",
  "section.cite": "How to cite",
  "section.organisation": "The organisation",
  "section.team": "Who we are",
  "section.summary": "Summary",
  "section.byType": "Actions by type",
  "section.log": "The log",
  "section.reports": "Reports",
  "section.chatbotsWeTest": "The chatbots we test",
  "section.attribution": "Attribution",
  "section.whereCited": "Where chatbots cited it",
  "section.complaints": "Complaints",
  "section.keyFindings": "Key findings",
  "section.scope": "Scope",
  "section.resultsByChatbot": "Results by chatbot and persona",
  "section.resultsByCountry": "Results by country and persona",
  "section.layerB": "Layer B: sources cited",
  "section.methodology": "Methodology",
  "section.byMonth": "Month by month",
  "section.byCountry": "By country and persona",
  "section.claimsRepeated": "Claims %s repeated",
  "section.reportsSentTo": "Reports we sent to %s",
  "section.whatChangedAfter": "What changed after we reported",
  "section.chatbotsTestedIn": "Chatbots tested in %s",
  "section.claimsRecordedIn": "Claims recorded in %s",
  "section.partners": "Local partners",

  "org.name": "Name",
  "org.legal": "Legal entity",
  "org.registered": "Registered in",
  "org.founded": "Founded",
  "org.diia": "Diia.City resident",
  "org.diiaSince": "since",
  "org.funding": "Funding",
  "org.fundingNote": "with no commercial relationship to any platform we test",
  "org.research": "Research and data",
  "org.platforms": "Platforms and trust & safety",
  "org.press": "Press",
  "org.corrections": "Corrections",

  "misc.methodologyVersion": "Methodology version %s. Watchlist version %s.",
  "misc.noAttribution": "No published attribution is recorded for this domain yet. We do not attribute networks ourselves, so this entry stays on the list only while the citation record stands.",
  "misc.noComplaints": "We have filed no abuse complaint about this domain.",
  "misc.noEscalations": "We have sent %s no report about the findings on this page yet.",
  "misc.disclosureNamed": "We publish the fact, the date and the status. We do not publish correspondence or the names of individuals at %s.",
  "misc.citeQuestions": "Questions about the data, or a request for extended access:",
  "misc.doi": "DOI:",
  "misc.observationsAs": "Observations as %s",
  "misc.reportPdf": "Report as PDF",
  "misc.watchlistVersion": "%s domains, list version %s.",
  "misc.escalationCounts": "%s actions, %s of them reports to platforms and registrars, %s answered.",
  "misc.medianResponse": "Median response time %s days.",
  "misc.escalationSummary": "%s reports sent · %s answered · %s confirmed changes"
};

const uk = {
  "skip": "Перейти до змісту",
  "menu": "Меню",
  "nav.main": "Головне",
  "nav.footer": "Підвал",
  "nav.breadcrumb": "Навігаційний ланцюжок",
  "nav.pageData": "Ця сторінка як дані",
  "nav.contents": "Зміст",

  "crumb.home": "Головна",
  "crumb.registry": "Реєстр",
  "crumb.sources": "Джерела",
  "crumb.escalations": "Ескалації",
  "crumb.methodology": "Методологія",
  "crumb.data": "Дані",
  "crumb.about": "Про нас",
  "crumb.reports": "Звіти",
  "crumb.chatbots": "Чат-боти",

  "updated.prefix": "Оновлено",
  "updated.licence": "Дані:",
  "updated.how": "Як ми вимірюємо",
  "footer.pageData": "Ця сторінка як дані:",
  "footer.licence": "Дані за ліцензією",

  "translation.missing": "Цю сторінку ще не перекладено українською. Нижче — англійський оригінал; цифри й дати однакові в обох мовах.",

  "action.browseRegistry": "Переглянути реєстр",
  "action.readReport": "Читати останній звіт",
  "action.escalationLog": "Переглянути журнал ескалацій",
  "action.whoWeAre": "Хто ми",
  "action.allClaims": "Усі твердження",
  "action.allInRegistry": "Усі %s тверджень у реєстрі",
  "action.allDomains": "Усі %s доменів у списку",
  "action.whatThisDomainIs": "що це за домен",

  "counter.claims": "задокументованих неправдивих тверджень",
  "counter.claimsFew": "задокументовані неправдиві твердження",
  "counter.claim": "задокументоване неправдиве твердження",
  "counter.answers": "проаналізованих відповідей чат-ботів",
  "counter.answersFew": "проаналізовані відповіді чат-ботів",
  "counter.answer": "проаналізована відповідь чат-бота",
  "counter.reports": "звернень до платформ",
  "counter.reportsFew": "звернення до платформ",
  "counter.report": "звернення до платформ",
  "counter.actionsLogged": "дій у журналі",
  "counter.reportsSent": "надісланих звернень",
  "counter.answered": "з відповіддю",
  "counter.confirmedChanges": "підтверджених змін",

  "col.claim": "Твердження",
  "col.cluster": "Кластер",
  "col.verdict": "Вердикт",
  "col.repeatedBy": "Повторили",
  "col.countries": "Країни",
  "col.country": "Країна",
  "col.escalation": "Ескалація",
  "col.updated": "Оновлено",
  "col.chatbot": "Чат-бот",
  "col.company": "Компанія",
  "col.language": "Мова",
  "col.persona": "Персона",
  "col.date": "Дата",
  "col.modelVersion": "Версія моделі",
  "col.behaviour": "Поведінка",
  "col.citedDomains": "Процитовані домени, пов'язані з Кремлем",
  "col.organisation": "Організація",
  "col.finding": "Висновок",
  "col.action": "Дія",
  "col.to": "Кому",
  "col.status": "Статус",
  "col.response": "Відповідь",
  "col.answers": "Відповідей",
  "col.repeated": "Повторив",
  "col.contextualised": "Уточнив",
  "col.refuted": "Спростував",
  "col.dodged": "Ухилився",
  "col.repeatRate": "Частка повторів",
  "col.before": "До",
  "col.after": "Після",
  "col.change": "Зміна",
  "col.measured": "Виміряно",
  "col.remeasured": "Повторний вимір",
  "col.month": "Місяць",
  "col.domain": "Домен",
  "col.firstSeen": "Перше цитування",
  "col.claims": "Твердження",
  "col.citedBy": "Цитували",
  "col.complaint": "Скарга",
  "col.dataset": "Набір даних",
  "col.format": "Формат",
  "col.contains": "Що містить",
  "col.report": "Звіт",
  "col.publishedOn": "Опубліковано",
  "col.chatbots": "Чат-боти",
  "col.count": "Кількість",
  "col.citedWatchlisted": "Процитував домен зі списку",

  "value.none": "немає",
  "value.notReported": "не вказано",
  "value.notRecorded": "не зафіксовано",
  "value.noneFiled": "не подавали",
  "value.na": "н/д",
  "value.dash": "—",

  "claim.verdict": "Вердикт",
  "claim.whatIsTrue": "Що є правдою",
  "claim.origin": "Звідки походить твердження",
  "claim.whoElse": "Хто ще це перевіряв",
  "claim.whichChatbots": "Які чат-боти його повторили",
  "claim.sourcesCited": "Джерела, на які посилалися чат-боти",
  "claim.whatWeDid": "Що ми зробили",
  "claim.whatChanged": "Що змінилося",
  "claim.changelog": "Журнал змін",
  "claim.cite": "Як цитувати цю сторінку",
  "claim.related": "Пов'язані твердження",
  "claim.official": "офіційно",
  "claim.cluster": "Кластер",
  "claim.verdictIssued": "Вердикт",
  "claim.id": "Ідентифікатор",

  "caption.observations": "Кожна зафіксована відповідь щодо цього твердження. Один рядок — одна відповідь; персони ніколи не усереднюються.",
  "caption.confirmations": "Незалежні організації, які дійшли того самого висновку.",
  "caption.actions": "Усе, що ми зробили щодо цього твердження, з датами.",
  "caption.beforeAfter": "Частка повторів до і після нашого звернення, за чат-ботом і персоною.",
  "caption.claims": "Усі задокументовані твердження, спершу нещодавно оновлені.",
  "caption.facetClaims": "Твердження в цьому зрізі, спершу нещодавно оновлені.",
  "caption.registration": "Реєстрація і статус.",
  "caption.contact": "Куди писати.",
  "caption.datasets": "Усі набори даних цього сайту. Усі за ліцензією CC BY 4.0.",
  "caption.escalationLog": "Кожна дія, спершу найновіші. Формулювання статусів фіксовані; нічого не позначаємо як «у процесі» без дати.",
  "caption.actionsByType": "Які саме дії ми вчиняли і як часто.",
  "caption.reports": "Усі звіти серії, спершу найновіші.",
  "caption.scope": "Що охопив цей прогін.",
  "caption.byChatbotPersona": "Один рядок — чат-бот і персона. Частка повторів рахується від відповідей по суті; ухилення виключені зі знаменника і показані окремо.",
  "caption.byCountryPersona": "Ті самі відповіді, згруповані за країною, з якої велася сесія.",
  "caption.layerB": "Відповіді з посиланням на домен зі списку, за чат-ботом і персоною.",
  "caption.byMonth": "Поведінка за місяцем і персоною. Частка повторів рахується від відповідей по суті.",
  "caption.platformClaims": "Задокументовані твердження, які цей чат-бот подав як факт щонайменше в одній зафіксованій відповіді.",
  "caption.platformEscalations": "Звернення щодо знахідок про цей продукт і статус відповіді.",
  "caption.platformBeforeAfter": "Частка повторів до і після кожного звернення, з версією моделі на обох вимірах.",
  "caption.countryClaims": "Задокументовані твердження, зафіксовані у відповідях для цієї країни.",
  "caption.platformIndex": "Усі чат-боти із зафіксованими відповідями. Кількості, а не усереднені частки: частки за персонами — у профілі кожного.",
  "caption.attribution": "Хто і коли атрибутував цей домен до мережі.",
  "caption.sourceClaims": "Твердження, у зафіксованих відповідях щодо яких цитували цей домен.",
  "caption.complaints": "Скарги на зловживання, які ми подали щодо цього домену.",
  "caption.watchlist": "Домени, атрибутовані до мережі %s, спершу найчастіше цитовані.",

  "note.persona": "Персони — це чотири способи поставити те саме питання, від нейтральної перевірки до прохання написати наратив. Кожен рядок — одна відповідь для однієї персони; ми не усереднюємо їх, бо модель може триматися на нейтральному питанні й поступитися на навідному.",
  "note.disclosure": "Ми публікуємо, що зробили, кому і коли. Ми не публікуємо листування і не називаємо працівників платформ.",
  "note.causation": "Моделі оновлюються постійно й незалежно від наших звернень. Ми фіксуємо версію на обох вимірах і публікуємо зміну, не приписуючи собі причинності, якої не можемо довести.",
  "note.defang": "Домени наведено в знешкодженому вигляді й без посилань, щоб ця сторінка не передавала їм ваги.",
  "note.publicInterface": "Ми тестуємо публічний користувацький інтерфейс, а не API. Версії записані так, як їх повідомив продукт, і результати можуть змінитися після оновлення продукту.",
  "note.metric": "Ми повідомляємо зміну частки повторів до і після, за кожним чат-ботом і кожною персоною.",

  "section.filter": "Фільтр",
  "section.howToRead": "Як читати цей реєстр",
  "section.allClaims": "Усі твердження",
  "section.findings": "Що ми виявили дотепер",
  "section.usedBy": "Де використовують наші дані",
  "section.whyTrust": "Чому нам можна вірити",
  "section.theProblem": "Аудиторія — це модель",
  "section.whatWeDo": "Що ми робимо",
  "section.downloads": "Завантаження",
  "section.cite": "Як цитувати",
  "section.organisation": "Організація",
  "section.team": "Хто ми",
  "section.summary": "Підсумок",
  "section.byType": "Дії за типом",
  "section.log": "Журнал",
  "section.reports": "Звіти",
  "section.chatbotsWeTest": "Чат-боти, які ми тестуємо",
  "section.attribution": "Атрибуція",
  "section.whereCited": "Де чат-боти його цитували",
  "section.complaints": "Скарги",
  "section.keyFindings": "Ключові висновки",
  "section.scope": "Охоплення",
  "section.resultsByChatbot": "Результати за чат-ботом і персоною",
  "section.resultsByCountry": "Результати за країною і персоною",
  "section.layerB": "Шар B: процитовані джерела",
  "section.methodology": "Методологія",
  "section.byMonth": "За місяцями",
  "section.byCountry": "За країною і персоною",
  "section.claimsRepeated": "Твердження, які повторив %s",
  "section.reportsSentTo": "Звернення, які ми надіслали до %s",
  "section.whatChangedAfter": "Що змінилося після звернення",
  "section.chatbotsTestedIn": "Чат-боти, протестовані в країні %s",
  "section.claimsRecordedIn": "Твердження, зафіксовані в країні %s",
  "section.partners": "Місцеві партнери",

  "org.name": "Назва",
  "org.legal": "Юридична особа",
  "org.registered": "Зареєстровано в",
  "org.founded": "Засновано",
  "org.diia": "Резидент Дія.City",
  "org.diiaSince": "з",
  "org.funding": "Фінансування",
  "org.fundingNote": "без комерційних відносин із жодною платформою, яку ми тестуємо",
  "org.research": "Дослідження і дані",
  "org.platforms": "Платформи і trust & safety",
  "org.press": "Преса",
  "org.corrections": "Виправлення",

  "misc.methodologyVersion": "Версія методології %s. Версія списку доменів %s.",
  "misc.noAttribution": "Для цього домену ще не зафіксовано опублікованої атрибуції. Ми не атрибутуємо мережі самостійно, тож цей запис лишається у списку лише поки стоїть запис про цитування.",
  "misc.noComplaints": "Ми не подавали скарг на зловживання щодо цього домену.",
  "misc.noEscalations": "Ми ще не надсилали до %s звернень щодо знахідок на цій сторінці.",
  "misc.disclosureNamed": "Ми публікуємо факт, дату і статус. Ми не публікуємо листування і не називаємо працівників %s.",
  "misc.citeQuestions": "Питання щодо даних або запит на розширений доступ:",
  "misc.doi": "DOI:",
  "misc.observationsAs": "Спостереження у форматі %s",
  "misc.reportPdf": "Звіт у PDF",
  "misc.watchlistVersion": "%s доменів, версія списку %s.",
  "misc.escalationCounts": "%s дій, з них %s звернень до платформ і реєстраторів, %s з відповіддю.",
  "misc.medianResponse": "Медіанний час відповіді %s днів.",
  "misc.escalationSummary": "%s надісланих звернень · %s з відповіддю · %s підтверджених змін"
};

module.exports = { en, uk };
