// Interface strings. Prose lives in content/; this file is chrome only.
// A missing Ukrainian key falls back to English rather than failing the build.
const en = {
  "skip": "Skip to content",
  "search": "Search claims, chatbots, domains",
  "nav.main": "Main",
  "nav.breadcrumb": "Breadcrumb",
  "demo.tag": "Demo data",
  "translation.missing": "This page has not been translated into Ukrainian yet. The text below is the English original; every figure and date is the same in both languages.",

  "crumb.home": "Home",
  "crumb.registry": "Registry",
  "crumb.benchmarks": "Benchmarks",
  "crumb.reports": "Reports",
  "crumb.chatbots": "Chatbots",
  "crumb.countries": "Countries",
  "crumb.sources": "Sources",
  "crumb.escalations": "Escalations",
  "crumb.methodology": "Methodology",
  "crumb.data": "Data",
  "crumb.about": "About",
  "crumb.mission": "Mission",
  "crumb.manifesto": "Manifesto",
  "crumb.press": "Press &amp; Media",
  "crumb.terms": "Terms",
  "crumb.privacy": "Privacy",

  "nav.registry": "Registry", "nav.benchmarks": "Benchmarks", "nav.reports": "Reports",
  "nav.chatbots": "Chatbots", "nav.sources": "Sources", "nav.escalations": "Escalations",
  "nav.methodology": "Methodology", "nav.countries": "Countries", "nav.data": "Data",
  "nav.about": "About", "nav.mission": "Mission", "nav.manifesto": "Manifesto",
  "nav.press": "Press &amp; Media", "nav.corrections": "Corrections", "nav.contact": "Contact",
  "nav.terms": "Terms", "nav.privacy": "Privacy", "nav.claimRegistry": "Claim registry",
  "nav.escalationLog": "Escalation log", "nav.dataDownloads": "Data &amp; downloads",
  "nav.howToCite": "How to cite", "nav.rss": "RSS", "nav.jsonFeed": "JSON Feed", "nav.llms": "llms.txt", "nav.security": "security.txt",
  "footer.monitoring": "Monitoring", "footer.method": "Method &amp; data", "footer.organisation": "Organisation",
  "footer.blurb": "Independent monitoring of public AI chatbots for Russian disinformation about Ukraine. Ukrainian research company, Diia.City resident.",
  "footer.licence": "Data under CC BY 4.0",
  "footer.updated": "Updated",

  "col.claim": "Claim", "col.verdict": "Verdict", "col.repeatedBy": "Repeated by",
  "col.status": "Status", "col.updated": "Updated", "col.chatbot": "Chatbot",
  "col.company": "Company", "col.country": "Country", "col.persona": "Persona",
  "col.date": "Date", "col.judge": "Judge", "col.organisation": "Organisation",
  "col.finding": "Finding", "col.repeatRate": "Repeat-rate", "col.contamination": "Contamination",
  "col.claimsRepeated": "Claims repeated", "col.escalations": "Escalations", "col.change": "Change",
  "col.responses": "Responses", "col.domain": "Domain", "col.network": "Network",
  "col.firstSeen": "First seen", "col.citedIn": "Cited in", "col.citations": "Citations",
  "col.citedBy": "Cited by", "col.type": "Type", "col.target": "Target", "col.response": "Response",
  "col.dataset": "Dataset", "col.format": "Format", "col.period": "Period", "col.cluster": "Cluster",
  "col.spread": "Spread", "col.before": "Before", "col.after": "After",

  "claim.verdict": "The verdict", "claim.whatIsTrue": "What is true",
  "claim.origin": "Where the claim comes from", "claim.whoElse": "Who else has checked this",
  "claim.whichChatbots": "Which chatbots repeated it", "claim.sourcesCited": "Sources the chatbots cited",
  "claim.whatWeDid": "What we did", "claim.whatChanged": "What changed", "claim.changelog": "Changelog",
  "claim.verdictIssued": "Verdict issued", "claim.grain": "Grain of truth",
  "claim.actionsTaken": "actions taken", "claim.platformResponses": "platform responses",
  "claim.remeasured": "re-measured", "claim.viewDomain": "View domain",
  "claim.getJson": "Get the JSON", "claim.getMarkdown": "Get the Markdown", "claim.cite": "Cite this page",
  "claim.showing": "Showing", "claim.of": "of", "claim.recordedAnswers": "recorded answers",
  "claim.everyAnswerJson": "Every answer as JSON",

  "section.latestFindings": "Latest findings", "section.rankings": "Rankings",
  "section.markets": "Markets we monitor", "section.usedBy": "Our data is used by",
  "section.howItWorks": "How it works", "section.whyTrust": "Why trust this",
  "section.leaderboards": "Leaderboards", "section.signature": "Signature measurements",
  "section.keyFindings": "Key findings", "section.resultsByChatbot": "Results by chatbot",
  "section.limitations": "Limitations", "section.byQuestionType": "By question type",
  "section.byCountry": "By country", "section.claimsRepeated": "Claims this chatbot repeated",
  "section.escalationsTo": "Escalations to", "section.assistantsHere": "Assistants in this market",
  "section.localPartners": "Local partners", "section.whereCited": "Where it was cited",
  "section.complaints": "Complaints filed", "section.articleEvidence": "Article evidence",
  "section.howToRead": "How to read this registry", "section.allClaims": "All claims",
  "section.sameClaim": "Same claim, four markets", "section.clustersWhere": "Which clusters are active where",
  "section.downloads": "Downloads",

  "action.browseRegistry": "Browse the registry", "action.latestReport": "Latest report",
  "action.howWeMeasure": "How we measure", "action.allRankings": "All rankings",
  "action.allCountries": "All countries", "action.readReport": "Read the report",
  "action.methodology": "Methodology", "action.citeRegistry": "Cite the registry",
  "action.downloadCsv": "Download CSV", "action.downloadLog": "Download the log (CSV)",
  "action.allBenchmarks": "All benchmarks", "action.download": "Download",
  "action.fullLogCsv": "The full log as CSV", "action.allInRegistry": "All %s claims in the registry",

  "value.none": "none", "value.notReported": "not reported", "value.dash": "—",
  "misc.assistantsWeTest": "Assistants we test", "misc.repeatRateRun": "repeat-rate",
  "misc.allActions": "All actions", "misc.allNetworks": "All networks",
  "misc.ofDocumented": "of %s documented", "misc.perPersonaNote": "Personas are reported separately and never averaged."
};

const uk = {
  "skip": "Перейти до змісту",
  "search": "Пошук тверджень, чат-ботів, доменів",
  "nav.main": "Головне",
  "nav.breadcrumb": "Навігаційний ланцюжок",
  "demo.tag": "Демодані",
  "translation.missing": "Цю сторінку ще не перекладено українською. Нижче — англійський оригінал; усі показники й дати однакові в обох мовах.",

  "crumb.home": "Головна", "crumb.registry": "Реєстр", "crumb.benchmarks": "Бенчмарки",
  "crumb.reports": "Звіти", "crumb.chatbots": "Чат-боти", "crumb.countries": "Країни",
  "crumb.sources": "Джерела", "crumb.escalations": "Ескалації", "crumb.methodology": "Методологія",
  "crumb.data": "Дані", "crumb.about": "Про нас", "crumb.mission": "Місія",
  "crumb.manifesto": "Маніфест", "crumb.press": "Преса", "crumb.terms": "Умови", "crumb.privacy": "Приватність",

  "nav.registry": "Реєстр", "nav.benchmarks": "Бенчмарки", "nav.reports": "Звіти",
  "nav.chatbots": "Чат-боти", "nav.sources": "Джерела", "nav.escalations": "Ескалації",
  "nav.methodology": "Методологія", "nav.countries": "Країни", "nav.data": "Дані",
  "nav.about": "Про нас", "nav.mission": "Місія", "nav.manifesto": "Маніфест",
  "nav.press": "Преса", "nav.corrections": "Виправлення", "nav.contact": "Контакти",
  "nav.terms": "Умови", "nav.privacy": "Приватність", "nav.claimRegistry": "Реєстр тверджень",
  "nav.escalationLog": "Журнал ескалацій", "nav.dataDownloads": "Дані та завантаження",
  "nav.howToCite": "Як цитувати", "nav.rss": "RSS", "nav.jsonFeed": "JSON Feed", "nav.llms": "llms.txt", "nav.security": "security.txt",
  "footer.monitoring": "Моніторинг", "footer.method": "Метод і дані", "footer.organisation": "Організація",
  "footer.blurb": "Незалежний моніторинг публічних AI-чат-ботів на російську дезінформацію про Україну. Українська дослідницька компанія, резидент Дія.City.",
  "footer.licence": "Дані за ліцензією CC BY 4.0",
  "footer.updated": "Оновлено",

  "col.claim": "Твердження", "col.verdict": "Вердикт", "col.repeatedBy": "Повторили",
  "col.status": "Статус", "col.updated": "Оновлено", "col.chatbot": "Чат-бот",
  "col.company": "Компанія", "col.country": "Країна", "col.persona": "Персона",
  "col.date": "Дата", "col.judge": "Суддя", "col.organisation": "Організація",
  "col.finding": "Висновок", "col.repeatRate": "Частка повторів", "col.contamination": "Забрудненість",
  "col.claimsRepeated": "Повторених тверджень", "col.escalations": "Ескалації", "col.change": "Зміна",
  "col.responses": "Відповідей", "col.domain": "Домен", "col.network": "Мережа",
  "col.firstSeen": "Перша фіксація", "col.citedIn": "Цитовано у", "col.citations": "Цитувань",
  "col.citedBy": "Цитували", "col.type": "Тип", "col.target": "Адресат", "col.response": "Відповідь",
  "col.dataset": "Набір даних", "col.format": "Формат", "col.period": "Період", "col.cluster": "Кластер",
  "col.spread": "Розкид", "col.before": "До", "col.after": "Після",

  "claim.verdict": "Вердикт", "claim.whatIsTrue": "Що є правдою",
  "claim.origin": "Звідки походить твердження", "claim.whoElse": "Хто ще це перевіряв",
  "claim.whichChatbots": "Які чат-боти його повторили", "claim.sourcesCited": "Джерела, на які посилалися чат-боти",
  "claim.whatWeDid": "Що ми зробили", "claim.whatChanged": "Що змінилося", "claim.changelog": "Журнал змін",
  "claim.verdictIssued": "Вердикт винесено", "claim.grain": "Зерно правди",
  "claim.actionsTaken": "виконаних дій", "claim.platformResponses": "відповідей платформ",
  "claim.remeasured": "повторний вимір", "claim.viewDomain": "Переглянути домен",
  "claim.getJson": "Отримати JSON", "claim.getMarkdown": "Отримати Markdown", "claim.cite": "Як цитувати цю сторінку",
  "claim.showing": "Показано", "claim.of": "з", "claim.recordedAnswers": "зафіксованих відповідей",
  "claim.everyAnswerJson": "Усі відповіді у JSON",

  "section.latestFindings": "Останні знахідки", "section.rankings": "Рейтинги",
  "section.markets": "Ринки, які ми моніторимо", "section.usedBy": "Наші дані використовують",
  "section.howItWorks": "Як це працює", "section.whyTrust": "Чому нам можна вірити",
  "section.leaderboards": "Рейтинги", "section.signature": "Ключові виміри",
  "section.keyFindings": "Ключові висновки", "section.resultsByChatbot": "Результати за чат-ботами",
  "section.limitations": "Обмеження", "section.byQuestionType": "За типом питання",
  "section.byCountry": "За країнами", "section.claimsRepeated": "Твердження, які повторив цей чат-бот",
  "section.escalationsTo": "Ескалації до", "section.assistantsHere": "Асистенти на цьому ринку",
  "section.localPartners": "Місцеві партнери", "section.whereCited": "Де його цитували",
  "section.complaints": "Подані скарги", "section.articleEvidence": "Докази на рівні статей",
  "section.howToRead": "Як читати цей реєстр", "section.allClaims": "Усі твердження",
  "section.sameClaim": "Те саме твердження, чотири ринки", "section.clustersWhere": "Які кластери де активні",
  "section.downloads": "Завантаження",

  "action.browseRegistry": "Переглянути реєстр", "action.latestReport": "Останній звіт",
  "action.howWeMeasure": "Як ми вимірюємо", "action.allRankings": "Усі рейтинги",
  "action.allCountries": "Усі країни", "action.readReport": "Читати звіт",
  "action.methodology": "Методологія", "action.citeRegistry": "Як цитувати реєстр",
  "action.downloadCsv": "Завантажити CSV", "action.downloadLog": "Завантажити журнал (CSV)",
  "action.allBenchmarks": "Усі бенчмарки", "action.download": "Завантажити",
  "action.fullLogCsv": "Повний журнал у CSV", "action.allInRegistry": "Усі %s тверджень у реєстрі",

  "value.none": "немає", "value.notReported": "не вказано", "value.dash": "—",
  "misc.assistantsWeTest": "Асистенти, яких ми тестуємо", "misc.repeatRateRun": "частка повторів",
  "misc.allActions": "Усі дії", "misc.allNetworks": "Усі мережі",
  "misc.ofDocumented": "з %s задокументованих", "misc.perPersonaNote": "Персони наводяться окремо і ніколи не усереднюються."
};

module.exports = { en, uk };
